### ISSUE TITLE
how create request to get url

### ISSUE THREAD

**Issue by googl24** [lscofield/node-urlresolver-api#1]
Hi,
How create request to get url?

**Comment by lscofield** [comment]
Hi, I'm still writing the documentation to make requests, but you can usually get a url like this: Assuming you've installed the API on your server. Check this pastebin code to get a jawcloud url with the fetch & axios libraries from nodejs.

https://pastebin.com/6vbqWpj2

**Comment by googl24** [comment]
thx for reply how send request in php pls?
