### ISSUE TITLE
How to use the api?

### ISSUE THREAD

**Issue by SolitaSolaa** [lscofield/node-urlresolver-api#10]
Hi, I don't know how to do work the api. The consults and the endpoints. Thanks.

**Comment by lscofield** [comment]
Hi, I'm still writing the documentation to make requests, but you can usually get a url like this: Assuming you've installed the API on your server. Check this pastebin code to get a direct url.
- Get cloudvideo url with the fetch & axios libraries from nodejs: https://pastebin.com/UBAVyyZc
- or get jawcloud url with php: https://pastebin.com/6vbqWpj2
