### ISSUE TITLE
need help with usage guide

### ISSUE THREAD

**Issue by talibnaik** [lscofield/node-urlresolver-api#11]
please guide how to use link this api

**Comment by lscofield** [comment]
Hi, I'm still writing the documentation to make requests, but you can usually get a url like this: Assuming you've installed the API on your server. Check this pastebin code to get a direct url.
- Get jawcloud url with the fetch & axios libraries from nodejs: https://pastebin.com/6vbqWpj2
- or get cloudvideo url with php: https://pastebin.com/UBAVyyZc

**Comment by talibnaik** [comment]
yes it is working fine but what about in the case of mixdrop?  if we run with curl it didn't get the file url
