### ISSUE TITLE
can you please guide usage of mixdrop?

### ISSUE THREAD

**Issue by kashifbutt123** [lscofield/node-urlresolver-api#12]
can you please guide usage of mixdrop?

**Comment by lscofield** [comment]
Hi, I'm still writing the documentation to make requests, but you can usually get a url like this: Assuming you've installed the API on your server. Check this pastebin code to get a direct url.
- Get jawcloud url with the fetch & axios libraries from nodejs: https://pastebin.com/6vbqWpj2
- or get cloudvideo url with php: https://pastebin.com/UBAVyyZc
- or get mixdrop url with php: https://pastebin.com/yEc9WyUe

**Comment by kashifbutt123** [comment]
awesome work.
