### ISSUE TITLE
I want to know about your experience with cloudvideo.tv

### ISSUE THREAD

**Issue by SorngSothearith** [lscofield/node-urlresolver-api#13]
when we use code to scrape real url like that.Is our video can be expired as it mention 60 day if no view our video will expire or delete.

**Comment by lscofield** [comment]
I don't know much about cloudvideo.  I don't upload videos, I only extract videos uploaded by other people.  The little I know is that the server that loads the fastest is mixdrop.co and those that can keep your videos without deleting with a premium option are doodstream, uptobox and others, you just have to investigate.
