### ISSUE TITLE
Powvideo not working on Google Cloud

### ISSUE THREAD

**Issue by orellanadaniel** [lscofield/node-urlresolver-api#14]
I am not sure if I am doing something wrong, everything was working fine in mi digitalocean server, when I implement your api (is awesome) the reponse for powvideo videos is empty, i tried with gamovideo and clipwatching, (both are ok), even in my all server powvideo response is correct but in my google cloud server the responde is empty. Do you have any idea what it can be?

Evidence: https://www.loom.com/share/de5c08169db44d80974268111efe0033

**Comment by lscofield** [comment]
You can debug it on your google server to see the error. I'm sure the error is from powvideo.php

**Comment by orellanadaniel** [comment]
> You can debug it on your google server to see the error. I'm sure the error is from powvideo.php

how can i do that, sorry I am new with nodejs

**Comment by lscofield** [comment]
You need to see if your servers/powvideo.js file
On the execPhp section, you can print a console.log(error) in the if(error) block or you can print printed or output... it is only for check if the php server work fine.

**Comment by orellanadaniel** [comment]
Error: Command failed: /usr/bin/php /home/daniel/py/seriesapi/node/url/node_modules/exec-php/lib/php/cli.php -p/tmp/tmp-4164Kr3jNQD3YChL.tmp -r/tmp/tmp-41648GE67alzSuIN.tmp
PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /home/daniel/py/seriesapi/node/url/lib/jsabc.php:7
Stack trace:
#0 [internal function]: {closure}(Array)
#1 /home/daniel/py/seriesapi/node/url/lib/jsabc.php(9): preg_replace_callback('@\\\\(x)?([0-9a-f...', Object(Closure), '<body>\n<div id=...')
#2 /home/daniel/py/seriesapi/node/url/lib/jsabc.php(106): decode_code('<body>\n<div id=...')
#3 /home/daniel/py/seriesapi/node/url/lib/powvideo.php(133): jsabc('<body>\n<div id=...')
#4 /home/daniel/py/seriesapi/node/url/node_modules/exec-php/lib/php/functions.php(28): powvideo('PGJvZHk+CjxkaXY...')
#5 /home/daniel/py/seriesapi/node/url/node_modules/exec-php/lib/php/cli.php(14): _exec_php_call_user_function('/home/daniel/py...', 'powvideo', Array)
#6 {main}
  thrown in /home/daniel/py/seriesapi/node/url/lib/jsabc.php on line 7

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 255,
  signal: null,
  cmd: '/usr/bin/php /home/daniel/py/seriesapi/node/url/node_modules/exec-php/lib/php/cli.php -p/tmp/tmp-4164Kr3jNQD3YChL.tmp -r/tmp/tmp-41648GE67alzSuIN.tmp'}

**Comment by lscofield** [comment]
Your Google server PHP version dont have install the php-mbstring extension for calling the mb_convert_encoding() function.
You need to run this command to install it and try again

$ sudo apt-get install php-mbstring

**Comment by orellanadaniel** [comment]
bro your the best, thanks now is ok, I was looking for an similar api long time ago, now my python app is complete
