### ISSUE TITLE
mixdrop extraction doesn't work 

### ISSUE THREAD

**Issue by fnicolo860** [lscofield/node-urlresolver-api#16]
for a few days the extraction on mixdrop no longer works, please can you fix it?

**Comment by lscofield** [comment]
Let me check

**Comment by fnicolo860** [comment]
> Let me check

News?

**Comment by lscofield** [comment]
Hello, the api work fine.
The problem is from mixdrop, now you need to extract the token in the first html and call mixdrop again with the token and then call the node-api: See this example implemented on java and tell me if it is work for you: 
https://pastebin.com/BzLHuQau

**Comment by fnicolo860** [comment]
can you give an example in php please?

**Comment by lscofield** [comment]
This is a checked example in PHP here: https://pastebin.com/yEc9WyUe
Tell me if it work for you

**Comment by Gujjugaming2k** [comment]
not working

**Comment by lscofield** [comment]
I will check it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
