### ISSUE TITLE
Seems to work just locally

### ISSUE THREAD

**Issue by ranaharoon** [lscofield/node-urlresolver-api#17]
is it supposed to work just local? after hosting the app it doesn't work. link is not useful anymore because of ip changed

**Comment by lscofield** [comment]
It is work perfectly, I have installed it in a vps hosting and it is work.

Just you need to get the html source from client side

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ranaharoon** [comment]
Even VPS hosted site has it's own IP while client side rendered HTML will consist it's own ip. How can you get client site html? it just works at local this way.

**Comment by lscofield** [comment]
I'm Android developer, I get the client html by make http request from java and I send it on my server API.
It is simple.

You cannot get the html source from your server, if yo do this, you goin to get IP issues.

If you are php developer you need to get client html source from javascript ajax but this is not possible by cors restriction.

The API is make for Apps, not for websites.

If you need to get the source from your own server and not get IP issues you need to pass client IP to your http request headers (not work in all websites)

Or you can use the hosts without IP restricction like supervideo, bitporno,...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ranaharoon** [comment]
Convenient answer. but please mention in information section that it's not for web based applications but just for android/desktop based applications. Thank you.
