### ISSUE TITLE
hey what are the parameters to be sent and requested from the api ?

### ISSUE THREAD

**Issue by Suyashjain05** [lscofield/node-urlresolver-api#19]
where will the skk key go ?
which parameter to send
can u please guide , i am getting 503 error when I'm trying to open directly server url.

**Comment by Suyashjain05** [comment]
i've deployed in on heroku.

**Comment by Suyashjain05** [comment]
while trying to test from your demo app, in most of the servers it's showing extraction error.

**Comment by lscofield** [comment]
Extraction error shown when the url it is down

**Comment by Suyashjain05** [comment]
ok

**Comment by W7orld** [comment]
> 
> 
> skk it is in the api config/conf.json
> Extraction error shown when the url it is down

Hello 
I'm trying use the node js app but not working give me an error say "Cannot GET /api/v1/clipwatching" HTTP response code is 404. Why i got this error what i missed?
