### ISSUE TITLE
Create request with php and jquery

### ISSUE THREAD

**Issue by googl24** [lscofield/node-urlresolver-api#2]
How create request with php and jquery?

**Comment by lscofield** [comment]
Hello, I can make it for you tomorrow, I currently bussy.

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by googl24** [comment]
Thhanks

**Comment by googl24** [comment]
Preferably only in php :)

**Comment by lscofield** [comment]
Here you have the code write in PHP to get direct cloudvideo url using API: https://pastebin.com/UBAVyyZc

**Comment by googl24** [comment]
thanks you are very helpful :)
