### ISSUE TITLE
how its work uptostream on php?

### ISSUE THREAD

**Issue by Pacifierjr** [lscofield/node-urlresolver-api#23]
how its work uptostream on php?

**Comment by lscofield** [comment]
Check the examples in README.md

**Comment by Pacifierjr** [comment]
yeah i see but i can't see for php example hehe

**Comment by lscofield** [comment]
Check this: https://pastebin.com/JSv1ykmF
It is for cloudvideo in php but is same for uptostream

**Comment by Pacifierjr** [comment]
i already try it but its blank only 
https://api.ykstream.com/serverlists/uptostream.php

i already test on clipwatching and mediafire and its work. but iptostream is not

http://api.ykstream.com/serverlists/clipwatching.php?link=https://clipwatching.com/jdicyolmn8wo
http://api.ykstream.com/serverlists/mediafire.php?link=https://www.mediafire.com/file/seckd06vf4ipatm/Donaciones.mp4/file

**Comment by Pacifierjr** [comment]
`<?php
 
/**
 * Getting direct cloudvideo URL 
 * using node-urlresolver-api API by @lscofield
 * This script is only tested with cloudvideo embed links
 */
 
// cloudvideo.tv test url 
// cloudvideo extraction work only with embed url
// You can test with another link if this link go down
$url = 'https://uptostream.com/ytbv2y53k063';
// Create curl instance (GET)
$ch = curl_init();
//Set the URL that you want to GET by using the CURLOPT_URL option.
curl_setopt($ch, CURLOPT_URL, $url);
//Set CURLOPT_RETURNTRANSFER so that the content is returned as a variable.
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
//Set CURLOPT_FOLLOWLOCATION to false to follow redirects.
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
// Set referer for mixdrop request 
curl_setopt($ch, CURLOPT_REFERER, $url);
 
//Execute the request.
$html = curl_exec($ch);
//Close the cURL handle.
curl_close($ch);
 
// Encode the html code to base64
$html = base64_encode($html);
$host = "uptostream"; // in this case
$api_endpoint = "https://api.ykstream.com/api/v1/$host";
// Prepare POST params
// Prepare auth param
$auth = '{"auth":"","skk":"eyJhdXRoIjoiIiwic2trIjoiTVlfS0VZIn0="}';
// Encode auth to base64
$auth = base64_encode($auth);
$params = array(
    "source" => $html,
    "auth" => $auth
);
 
$params = json_encode($params);
// Create curl instance (POST) to get direct
// URL with API
$ch = curl_init($api_endpoint);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLINFO_HEADER_OUT, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $params);
// Set HTTP Header for POST request 
curl_setopt(
    $ch,
    CURLOPT_HTTPHEADER,
    array(
        'Content-Type: application/json',
        'Content-Length: ' . strlen($params)
    )
);
// Submit the POST request
$result = curl_exec($ch);
// Close cURL session handle
curl_close($ch);
 
 
if ($result) {
    // Convert to json
    $result = json_decode($result);
    // Print direct url (format: .mp4)
    echo $result->url;
    // Note if the app_key set in post auth
    // not match with the app_key that you
    // has in your server config file
    // $resul->url will have a random troll mp4 video
    // If mixdrop url is down $result->url will have empty string
} else {
    // No data fetched
    // Typically API or SERVER issue
}`

**Comment by lscofield** [comment]
Let me check

**Comment by Pacifierjr** [comment]
okay thanks :)
