### ISSUE TITLE
Pls Help me,My question is which server i have to use

### ISSUE THREAD

**Issue by Rishi9440** [lscofield/node-urlresolver-api#27]
I don't know about servers well, pls recommend me any server hosting company
so that I can set up this API, can I use Heroku will it work with Heroku?

**Comment by lscofield** [comment]
Hello, I dont know about heroku, yoy can use contabo.com or ovh.com to get a vps server.

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________
