### ISSUE TITLE
Mixdrop 403 forbieden

### ISSUE THREAD

**Issue by googl24** [lscofield/node-urlresolver-api#3]
Hi why mixdrop get url 403 forbieden in php? Pls repair it

**Comment by lscofield** [comment]
Mixdrop not have any issue, I already checked it and it work perfectly: Please check this code to see how to get mixdrop direct url, it's exactly like cloudvideo but you need to read it: https://pastebin.com/yEc9WyUe

**Comment by googl24** [comment]
i generate link https://a-delivery3.mxdcontent.net/v/f95ca07474e39e0eae428fa97c752f37.mp4?s=xcT82Hl8GHgeY3fy4uppHg&e=1582053516 when i click i see 403 Forbidden

**Comment by lscofield** [comment]
You have looked at the code I send you? You have comented part say:
"Note to play this video in a videoplayer
you need to pass $url to http referer header in these player to be play
 Other wise you will get ERROR 404 or similar in the media player"

**Comment by googl24** [comment]
sorry i have not seen that :/ 
How pass url to http refer header? i search in google and not seen

**Comment by lscofield** [comment]
I have reviewed your case again and your error occurs because you are probably trying to get the url from your php server and then try to reproduce it from your computer.  Keep in mind that the IP address with which you get the html should be the same as the one you play with.

**Comment by googl24** [comment]
i change result code to
`echo '<iframe width="420" height="315" src="'. $result->url.'"></iframe>';`
and i see 403 error :/

**Comment by lscofield** [comment]
I repeat. If you are trying to play this video from diferent IP that you get the html code you will receive this error. Please play the video from client side (not server side)
