### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by VyperJC** [lscofield/node-urlresolver-api#5]
How I can use this API? with no documentation is not easy understand how this API work... thanks

**Comment by lscofield** [comment]
I am currently writing the documentation, but if you want you can look at those examples of how to get direct link from mixdrop, cloudvideo and jawcloud.

jawcloud (example in nodejs): https://pastebin.com/6vbqWpj2
mixdrop (example with php): https://pastebin.com/yEc9WyUe
cloudvideo (example with php): https://pastebin.com/UBAVyyZc
