### ISSUE TITLE
Ok.ru can not play video

### ISSUE THREAD

**Issue by SorngSothearith** [lscofield/node-urlresolver-api#6]
Hello when I use to get stream video url from ok.ru it got only number 10.
https://vd43.mycdn.me/?expires=1586896886682&srcIp=114.134.185.207&srcAg=UNKNOWN&ms=217.20.157.211&type=4&sig=fGgIbdwDQHE&ct=0&urls=217.20.153.78&clientType=0&id=1055588682240

**Comment by lscofield** [comment]
Check it in a video player please and pass https://ok.ru/ in the referer header

**Comment by SorngSothearith** [comment]
I just use videojs player for that and it still doesn't work.I didnt clear about referer header ok.ru yet can you make its details?

**Comment by SorngSothearith** [comment]
Another thing I wish I can create API to mobile phone app with flutter if it possible by using your respo?

**Comment by lscofield** [comment]
You can create any app you need, I have an Android App that work fine with the API, I use exoplayer to play these video (ok.ru videos work perfectly)

**Comment by SorngSothearith** [comment]
You mean exoplayer for android right? How about the web browser what you using now?
