### ISSUE TITLE
Can you tell me the library for js to play that media (for ok.ru)?

### ISSUE THREAD

**Issue by SorngSothearith** [lscofield/node-urlresolver-api#8]
I played it via VLC player in my computer it worked but when I use to play with videojs jw player afterglowplayer it not working.Can you tell me the library for js to play that media?
<img width="1680" alt="Screen Shot 2020-04-15 at 3 19 13 PM" src="https://user-images.githubusercontent.com/38551750/79319484-939f3b80-7f32-11ea-8d2f-71b6db93a6e6.png">
<img width="1680" alt="Screen Shot 2020-04-15 at 4 02 24 PM" src="https://user-images.githubusercontent.com/38551750/79319485-96019580-7f32-11ea-9599-b255cdec74bc.png">

**Comment by lscofield** [comment]
I don't use web player, but I just checked that the ok.ru links don't play on the web player.  Let me investigate to see if I find a solution.

**Comment by SorngSothearith** [comment]
Yes, brother. I currently stuck on that point for half month now. Please help me with that.I appreciate your work.

**Comment by SorngSothearith** [comment]
When I debug it I saw it want vdsig what vsig for the end of it.
https://vd3.mycdn.me/?expires=1587032321376&srcIp=114.134.185.252&srcAg=CHROME_MAC&ms=217.20.145.39&type=2&sig=xv-f_dIIk4Q&ct=0&urls=217.20.157.196&clientType=0&id=433054288520&vdsig=15GMKD7IM7z8wYqWhvyELuMXEJA

**Comment by lscofield** [comment]
I have found a possible the solution, but I don't know if you can implement it in a web player. 
1.- Make request to get the html source from ok.ru video with the {"user-agent": "Mozilla"} header  2.- Extract the url with the node-urlresolver-api to get direct url.
3.- Open the player passing the {"user-agent": "(Android) ExoPlayerLib/2.9.6"} header.
4.- Enjoy the video.

Note: I don't know if you can change the video player header in a web app but it work fine with native apps!!

Try that, I'll keep looking at other solutions and you have other servers in case ok.ru gives you problems.
